return {
    ConfigName = "Character",
    SrcConfigRefName = "京畿女",
    DestConfigRefName = "TaiwuGoodPartnerAya.Aya",
    TemplateId = 12001,

    Data = {
        Surname = "",
        GivenName = "阿雅",
        AnonymousTitle = "太吾好伙伴",
        CreatingType = 0,
        CanOpenCharacterMenu = false,
        IsFavorabilityDisplay = false,
        HideAge = false,
        CanSpeak = true,
        CanBeTaiwu = false,
        CanBePossessionBody = false,
        CanBePossessionSoul = false,
        FixedCharacterShowNameOnMap = true,
        CanDefeat = false,
        AllowEscape = true,
        AllowHeal = true,
        CanBeKidnapped = false,
        RandomAnimalAttack = false,
        XiangshuInfectedDemonBonus = false,
        RandomFeaturesAtCreating = false,
        Gender = 1,
        Race = 0,
        PresetBodyType = 0,
        FixedAvatarName = "NpcFace_taiwu_good_partner_aya",
        BaseAttraction = 900,
        Happiness = 50,
        Health = 100,
        BaseMaxHealth = 100,
        FatalImmunity = true,
        DieImmunity = true,
        InnerInjuryImmunity = true,
        OuterInjuryImmunity = true,
        MindImmunity = true,
        FlawImmunity = true,
        AcupointImmunity = true,
        ActualAge = 19,
        InitCurrAge = 19,
        BirthMonth = 3,
    },
}
